# версия спецификации файла
version: '3'
# основной раздел, где мы создаем и описываем наши сервисы (контейнеры docker)
services:
  # название для нашего сервиса - hub_nginx, на основе которого будет создан контейнер
  hub_nginx:
    # имя образа, который будет использоваться для создания контейнера
    image: nginx:latest
    # имя, которое получен созданный контейнер
    container_name: srv-nginx-2
    # указываем на каких портах должен слушать контейнер и на какие порты должны пробрасываться запросы
    ports: 
      - 80:8080
    #  зависимости для контейнеров. В конкретном примере, контейнер не запустится, пока не поднимется my_nginx
    depends_on:
      - my_nginx
    #  проброс папок. Мы смонтируем локальный каталог ./nginx.conf на хосте внутрь контейнера в качестве каталога /etc/nginx/nginx.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  my_nginx:
    image: nginx-img:2.0.0
    container_name: srv-nginx-1