#-----------------------------------------
# GitHub Action DevOps
#
# Copyleft (c) by Malikov Andrey 2022
#-----------------------------------------
name: DevOps_Repository

on:
  push:
    branches: 
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Commit in branch main
        run : echo "The project has been COMMITTED. Status is OK."
  
  deploy:
    runs-on: ubuntu-latest
    needs: [commit]
    
    steps:
      - name: Deploy project
        run: echo "The project was DEPLOED. Status is OK."
