#-----------------------------------------
# GitHub Action DevOps
#
# Copyleft (c) by Malikov Andrey 2022
#-----------------------------------------
name: DevOps_Repository
env:
  REPOSITORY: "Repository-name-is-${{ github.repository }}"
  DEPLOY    : "Deploy-status-ver-${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Status commit in branch main
        run : echo "The project has been COMMITTED. Status is OK."
        
      - name: Repository name
        run : echo "${{ env.REPOSITORY }}"
  
  deploy:
    runs-on: ubuntu-latest
    needs: [commit]
    
    steps:
      - name: Status deploy project
        run: echo "The project was DEPLOED. Status is OK."
        
      - name: Version
        run : |
          echo "${{ env.DEPLOY }}"
